import { useState, useEffect } from "react";

// ✅ All translations for the whole website
const translations = {
  en: {
    // ===== NAVBAR =====
    home:     "Home",
    services: "Services",
    pricing:  "Pricing",
    about:    "About",
    reviews:  "Reviews",
    contact:  "Contact",
    bookNow:  "Book Now",

    // ===== HOME PAGE =====
    heroBadge:       "Professional Cleaning Services",
    heroTitle1:      "A Cleaner Home,",
    heroTitle2:      "A Happier Life",
    heroSubtitle:    "J & S Palvelut delivers professional, eco-friendly cleaning services for homes and offices in Helsinki. Founded in 2023, trusted by customers across the city.",
    bookCleaning:    "Book a Cleaning",
    viewServices:    "View Services",
    happyCustomers:  "Happy Customers",
    avgRating:       "Average Rating",
    yearsExp:        "Years Experience",
    homeClean:       "Home Cleaning",
    officeClean:     "Office Cleaning",
    deepClean:       "Deep Cleaning",
    ecoFriendly:     "Eco Friendly",

    // ===== FEATURES =====
    whyChooseUs:    "Why Choose J & S Palvelut?",
    whySubtitle:    "We make cleaning easy, reliable, and worry-free — so you can focus on what matters most to you.",
    ecoTitle:       "Eco-Friendly Products",
    ecoDesc:        "We use only non-toxic, biodegradable cleaning products that are safe for your family and pets.",
    flexTitle:      "Flexible Scheduling",
    flexDesc:       "Book a cleaning at any time that works for you — mornings, evenings, or weekends.",
    vettedTitle:    "Vetted Professionals",
    vettedDesc:     "Every cleaner is background-checked, trained, and insured for your peace of mind.",
    transTitle:     "Transparent Pricing",
    transDesc:      "No hidden fees. You see the full price before you book — always fair and honest.",
    guarTitle:      "Satisfaction Guarantee",
    guarDesc:       "Not happy? We will come back and re-clean for free, no questions asked.",
    easyTitle:      "Easy Online Booking",
    easyDesc:       "Book, reschedule, or cancel in seconds from your phone or computer.",

    // ===== SERVICES HOME PREVIEW =====
    ourServices:    "Our Cleaning Services",
    ourServicesDesc:"From regular home cleaning to deep cleans and office services — we have a plan for every need and budget.",
    viewAll:        "View All Services →",

    // ===== CTA =====
    ctaTitle:       "Ready for a Sparkling Clean Home?",
    ctaSubtitle:    "Book your first cleaning today and get 20% off. No contracts, no commitments — just a cleaner home.",
    bookOff:        "Book Now — 20% Off",
    contactUs:      "Contact Us",
    noContracts:    "No contracts",
    insured:        "Insured & vetted",
    ecoFriendlyBadge: "Eco-friendly",
    rated:          "4.9 rated",

    // ===== SERVICES PAGE =====
    servicesBadge:  "What We Offer",
    servicesTitle1: "Cleaning Services",
    servicesTitle2: "For Every Need",
    servicesDesc:   "From regular home cleaning to deep cleans, office services, and move-in/move-out — we have a professional solution for every situation.",
    serviceTypes:   "8 Service Types",
    allServices:    "All Services",
    homeFilter:     "Home",
    officeFilter:   "Office",
    specialistFilter: "Specialist",
    bookNowBtn:     "Book Now",

    // ===== HOW IT WORKS =====
    howItWorks:     "How It Works",
    howSubtitle:    "Getting your home cleaned is simple — just 4 easy steps.",
    step1Title:     "Choose a Service",
    step1Desc:      "Browse our services and pick the one that fits your needs and budget.",
    step2Title:     "Pick a Date & Time",
    step2Desc:      "Select a date and time that works for you — mornings, evenings, or weekends.",
    step3Title:     "We Clean Your Space",
    step3Desc:      "Our vetted, professional cleaner arrives on time and does a perfect job.",
    step4Title:     "Enjoy & Review",
    step4Desc:      "Relax in your clean home and leave a review to help other customers.",
    bookYourCleaning: "Book Your Cleaning Now",

    // ===== PRICING PAGE =====
    pricingBadge:   "Simple, Transparent Pricing",
    pricingTitle1:  "Plans That Fit",
    pricingTitle2:  "Every Budget",
    pricingDesc:    "No hidden fees, no contracts. Pick the plan that works for you and get a sparkling clean home every time.",
    noContractsBadge: "No contracts",
    cancelAnytime:  "Cancel anytime",
    satisfactionGuar: "Satisfaction guarantee",
    monthly:        "Monthly",
    yearly:         "Yearly",
    save20:         "Save 20%",
    perMonth:       "/month",
    allPlansInclude: "All plans include our satisfaction guarantee. Not happy? We re-clean for free.",
    vatNotice:      "Prices exclude VAT (ALV 24%)",
    vatDesc:        "All prices shown are before VAT. Final invoice will include 24% ALV.",
    kotivah:        "Kotitalousvahennys — Save up to 40%!",
    kotivahDesc:    "Finnish customers can claim a household tax deduction of up to 40% on cleaning services. Ask us for more details!",

    // ===== FAQ =====
    faqTitle:       "Frequently Asked Questions",
    faqSubtitle:    "Everything you need to know about our pricing and plans.",
    stillQuestions: "Still have questions? We are happy to help!",

    // ===== ABOUT PAGE =====
    aboutBadge:     "Our Story",
    aboutTitle1:    "Cleaning Homes,",
    aboutTitle2:    "Building Trust",
    aboutSubtitle:  "J & S Palvelut Oy was founded in 2023 with one simple belief — everyone deserves a clean, comfortable home without the stress. Based in Helsinki, we serve customers across the city.",
    yearFounded:    "Year Founded",
    teamMembers:    "Team Members",
    revenue2024:    "Revenue 2024",
    ourJourney:     "Our Journey",
    journeySubtitle:"From a small startup to Helsinki's most trusted cleaning service — here is how we got here.",
    meetTeam:       "Meet the Team",
    teamSubtitle:   "The dedicated people behind every sparkling clean home.",
    whatWeStandFor: "What We Stand For",
    valuesSubtitle: "Our values are at the heart of everything we do.",
    joinTeam:       "Want to Join Our Team?",
    joinDesc:       "We are always looking for reliable, friendly people who take pride in their work. Great pay, flexible hours, and a supportive team.",
    getInTouch:     "Get in Touch",
    // ===== ABOUT PAGE — add these missing keys =====
avgRating:       "Average Rating",
milestone1Title: "Founded in Helsinki",
milestone1Desc:  "J & S Palvelut Oy was officially registered on 28 March 2023 by Jamanta and Shapan. Starting with just 1 employee and a vision to provide reliable cleaning services in Helsinki.",
milestone2Title: "First Year Success",
milestone2Desc:  "In our first year we achieved 26,000 euros in revenue with a strong 16.7% profit margin. Word spread quickly about our reliable and professional service.",
milestone3Title: "Strong Growth",
milestone3Desc:  "Revenue grew by 103.9% to 53,000 euros in 2024. Our team grew to 3 employees. We expanded our services to cover more areas across Helsinki.",
milestone4Title: "Building the Future",
milestone4Desc:  "We continue to grow our customer base and improve our services. Our goal is to become Helsinki's most trusted cleaning service for both homes and offices.",
ceoRole:         "CEO & Co-Founder",
ceoBio:          "Jamanta co-founded J & S Palvelut Oy in 2023. He leads the company with a strong focus on quality service and customer satisfaction across Helsinki.",
deputyRole:      "Deputy CEO & Co-Founder",
deputyBio:       "Shapan co-founded J & S Palvelut Oy and manages day-to-day operations. He ensures every cleaning meets the highest standards and every customer is happy.",
teamName3:       "Our Cleaning Team",
teamRole3:       "Professional Cleaners",
teamBio3:        "Our dedicated team of professional cleaners are trained, insured, and passionate about delivering spotless results every time.",

    // ===== VALUES =====
    trustTitle:     "Trust",
    trustDesc:      "Every cleaner is background-checked and insured. You can leave us your keys with complete confidence.",
    qualityTitle:   "Quality",
    qualityDesc:    "We never cut corners. Every clean is done to the highest standard — or we come back and do it again for free.",
    sustainTitle:   "Sustainability",
    sustainDesc:    "We care about the planet. All our products are eco-friendly, biodegradable, and safe for your family.",
    commTitle:      "Communication",
    commDesc:       "We keep you informed at every step. You will always know when your cleaner is on the way.",

    // ===== REVIEWS PAGE =====
    reviewsBadge:   "Customer Reviews",
    reviewsTitle1:  "What Our Customers",
    reviewsTitle2:  "Are Saying",
    reviewsSubtitle:"Don't just take our word for it — here is what real customers say about their J & S Palvelut experience.",
    basedOn:        "Based on 2,000+ reviews",
    allReviews:     "All Reviews",
    homeCleaning:   "Home Cleaning",
    deepCleanFilter:"Deep Clean",
    officeFilter2:  "Office",
    loadMore:       "Load More Reviews",
    verifiedCustomer: "Verified Customer",
    joinCustomers:  "Join 2,000+ Happy Customers",
    joinDesc2:      "Experience the J & S Palvelut difference for yourself. Book today and see why our customers keep coming back.",
    verifiedReviews: "2,000+ verified reviews",

    // ===== CONTACT PAGE =====
    contactBadge:   "Get In Touch",
    contactTitle1:  "We Would Love To",
    contactTitle2:  "Hear From You",
    contactSubtitle:"Have a question about our services? Want to get a custom quote? Or just want to say hello? We are here to help!",
    sendMessage:    "Send Us a Message",
    formSubtitle:   "Fill in the form and we will get back to you within 24 hours.",
    fullName:       "Full Name",
    emailAddr:      "Email Address",
    phoneOpt:       "Phone Number (optional)",
    serviceInterest:"Service You Are Interested In",
    selectService:  "Select a service...",
    yourMessage:    "Your Message",
    sendBtn:        "Send Message",
    sending:        "Sending...",
    successMsg:     "Message sent successfully!",
    successSub:     "We will get back to you within 24 hours.",
    errorMsg:       "Something went wrong. Please try again.",
    otherWays:      "Other Ways to Reach Us",
    fastResponse:   "Fast Response Guaranteed",
    fastDesc:       "We reply to all messages within 24 hours — usually much faster!",
    findUs:         "Find Us in Helsinki",
    findDesc:       "Based in Helsinki, serving customers across the city and surrounding areas.",
    areasServed:    "Areas We Serve",
    areaDesc:       "Not sure if we cover your area? Just send us a message and we will let you know!",
    workingHours:   "Mon-Fri: 8am-6pm",
    workingSat:     "Sat: 9am-3pm  |  Sun: Closed",

    // ===== BOOKING PAGE =====
    bookingBadge:   "Easy Online Booking",
    bookingTitle1:  "Book Your",
    bookingTitle2:  "Cleaning Service",
    bookingSubtitle:"Choose your service, pick a date and time, and we will take care of the rest. Takes less than 2 minutes!",
    chooseService:  "1. Choose service",
    pickDateTime:   "2. Pick date & time",
    yourDetails:    "3. Your details",
    confirm:        "4. Confirm",
    chooseServiceTitle: "Choose a Service",
    chooseServiceDesc:  "Select the cleaning service that best fits your needs.",
    pickDateTitle:  "Pick a Date & Time",
    pickDateDesc:   "Select your preferred date and time slot. Sundays are unavailable.",
    detailsTitle:   "Your Details",
    detailsDesc:    "Tell us where to clean and how to reach you.",
    confirmTitle:   "Confirm Your Booking",
    confirmDesc:    "Please review your booking details before confirming.",
    nameRequired:   "Name is required",
    emailRequired:  "Email is required",
    addrRequired:   "Address is required",
    selectDate:     "Please select a date",
    selectTime:     "Please select a time",
    selectServiceErr: "Please select a service",
    namePlaceholder:"Your full name",
    emailPlaceholder:"your@email.com",
    phonePlaceholder:"+358 xx xxx xxxx",
    addrPlaceholder:"Street address, city, postcode",
    notesPlaceholder:"Any special requests, allergies, access instructions...",
    specialInstructions: "Special Instructions (optional)",
    cleaningAddress:"Cleaning Address",
    back:           "Back",
    continue:       "Continue",
    confirmBooking: "Confirm Booking",
    bookingConfirmed: "Booking Confirmed!",
    bookingThankYou:"Your cleaning is booked. We will send a confirmation to",
    bookAnother:    "Book Another Cleaning",
    termsNotice:    "By confirming you agree to our terms of service. You can cancel or reschedule up to 24 hours before your booking.",
    service:        "Service",
    price:          "Price",
    duration:       "Duration",
    date:           "Date",
    time:           "Time",
    name:           "Name",
    email:          "Email",
    address:        "Address",
    selectTime2:    "Select a Time",
  },

  fi: {
    // ===== NAVBAR =====
    home:     "Etusivu",
    services: "Palvelut",
    pricing:  "Hinnat",
    about:    "Meista",
    reviews:  "Arvostelut",
    contact:  "Yhteystiedot",
    bookNow:  "Varaa nyt",

    // ===== HOME PAGE =====
    heroBadge:       "Ammattimaiset siivouspalvelut",
    heroTitle1:      "Puhtaampi koti,",
    heroTitle2:      "onnellisempi elama",
    heroSubtitle:    "J & S Palvelut tarjoaa ammattimaisia, ymparistoystavallisia siivouspalveluja koteihin ja toimistoihin Helsingissa. Perustettu 2023, luotettu asiakkaiden kesken ympari kaupungin.",
    bookCleaning:    "Varaa siivous",
    viewServices:    "Katso palvelut",
    happyCustomers:  "Tyytyvaista asiakasta",
    avgRating:       "Keskimaarainen arvosana",
    yearsExp:        "Vuotta kokemusta",
    homeClean:       "Kotisiivous",
    officeClean:     "Toimistosiivous",
    deepClean:       "Syvassiivous",
    ecoFriendly:     "Ymparistoystavallinen",

    // ===== FEATURES =====
    whyChooseUs:    "Miksi valita J & S Palvelut?",
    whySubtitle:    "Teemme siivouksesta helppoa, luotettavaa ja huoletonta — jotta voit keskittya siihen, mika on sinulle tarkeinta.",
    ecoTitle:       "Ymparistoystavallinen tuotteet",
    ecoDesc:        "Kaytamme vain myrkyttomia, biohajoavia puhdistustuotteita, jotka ovat turvallisia perheellesi ja lemmikeillesi.",
    flexTitle:      "Joustava aikataulu",
    flexDesc:       "Varaa siivous milloin tahansa — aamuisin, iltaisin tai viikonloppuisin.",
    vettedTitle:    "Tarkistetut ammattilaiset",
    vettedDesc:     "Jokainen siivooja on taustatarkistettu, koulutettu ja vakuutettu.",
    transTitle:     "Lapi naky va hinnoittelu",
    transDesc:      "Ei piilomaksuja. Naet koko hinnan ennen varausta — aina reilu ja rehellinen.",
    guarTitle:      "Tyytyvaistakuu",
    guarDesc:       "Et ole tyytyvainen? Tulemme siivoamaan uudelleen ilmaiseksi, ilman kysymyksia.",
    easyTitle:      "Helppo verkkovaraus",
    easyDesc:       "Varaa, muuta tai peruuta varaus sekunneissa puhelimellasi tai tietokoneellasi.",

    // ===== SERVICES HOME PREVIEW =====
    ourServices:    "Siivouspalvelumme",
    ourServicesDesc:"Tavallisesta kotisiivouksesta syvasiivoukseen ja toimistopalveluihin — meilla on ratkaisu jokaiseen tarpeeseen ja budjettiin.",
    viewAll:        "Katso kaikki palvelut",

    // ===== CTA =====
    ctaTitle:       "Valmis kiiltavan puhtaaseen kotiin?",
    ctaSubtitle:    "Varaa ensimmainen siivous tanaan ja saat 20% alennuksen. Ei sopimuksia, ei sitoutumista — vain puhtaampi koti.",
    bookOff:        "Varaa nyt — 20% alennus",
    contactUs:      "Ota yhteytta",
    noContracts:    "Ei sopimuksia",
    insured:        "Vakuutettu ja tarkistettu",
    ecoFriendlyBadge: "Ymparistoystavallinen",
    rated:          "4.9 arvioitu",

    // ===== SERVICES PAGE =====
    servicesBadge:  "Mita tarjoamme",
    servicesTitle1: "Siivouspalvelut",
    servicesTitle2: "jokaiseen tarpeeseen",
    servicesDesc:   "Tavallisesta kotisiivouksesta syvasiivoukseen, toimistopalveluihin ja muutto siivoukseen — meilla on ammattimainen ratkaisu jokaiseen tilanteeseen.",
    serviceTypes:   "8 palvelutyyppia",
    allServices:    "Kaikki palvelut",
    homeFilter:     "Koti",
    officeFilter:   "Toimisto",
    specialistFilter: "Erikoispalvelut",
    bookNowBtn:     "Varaa nyt",

    // ===== HOW IT WORKS =====
    howItWorks:     "Miten se toimii",
    howSubtitle:    "Kotisi siivous on helppoa — vain 4 yksinkertaista vaihetta.",
    step1Title:     "Valitse palvelu",
    step1Desc:      "Selaa palvelujamme ja valitse tarpeisiisi sopiva.",
    step2Title:     "Valitse paiva ja aika",
    step2Desc:      "Valitse sinulle sopiva paiva ja aika — aamuisin, iltaisin tai viikonloppuisin.",
    step3Title:     "Siivoamme tilasi",
    step3Desc:      "Ammattisiivooamme saapuu ajoissa ja tekee erinomaisen tyon.",
    step4Title:     "Nauti ja arvioi",
    step4Desc:      "Rentoudu puhtaassa kodissasi ja jata arvostelu auttaaksesi muita asiakkaita.",
    bookYourCleaning: "Varaa siivous nyt",

    // ===== PRICING PAGE =====
    pricingBadge:   "Yksinkertainen, lapi naky va hinnoittelu",
    pricingTitle1:  "Suunnitelmat jokaiselle",
    pricingTitle2:  "budjetille",
    pricingDesc:    "Ei piilomaksuja, ei sopimuksia. Valitse sinulle sopiva suunnitelma ja saat aina puhtaan kodin.",
    noContractsBadge: "Ei sopimuksia",
    cancelAnytime:  "Peruuta milloin tahansa",
    satisfactionGuar: "Tyytyvaistakuu",
    monthly:        "Kuukausittain",
    yearly:         "Vuosittain",
    save20:         "Saasta 20%",
    perMonth:       "/kuukausi",
    allPlansInclude:"Kaikki suunnitelmat sisaltavat tyytyvaistakuun. Et ole tyytyvainen? Siivoamme uudelleen ilmaiseksi.",
    vatNotice:      "Hinnat sisaltavat ALV 24%",
    vatDesc:        "Kaikki hinnat on ilmoitettu ennen ALVia. Lopullinen lasku sisaltaa 24% ALVin.",
    kotivah:        "Kotitalousvahennys — Saasta jopa 40%!",
    kotivahDesc:    "Suomalaiset asiakkaat voivat vaatia kotitalousvahennysta jopa 40% siivouspalveluiden tyokustannuksista. Kysy meilta lisatietoja!",

    // ===== FAQ =====
    faqTitle:       "Usein kysytyt kysymykset",
    faqSubtitle:    "Kaikki mita sinun tulee tietaa hinnoittelustamme ja suunnitelmistamme.",
    stillQuestions: "Onko sinulla viela kysymyksia? Autamme mielellaamme!",

    // ===== ABOUT PAGE =====
    aboutBadge:     "Tarinamme",
    aboutTitle1:    "Siivoamme koteja,",
    aboutTitle2:    "rakennamme luottamusta",
    aboutSubtitle:  "J & S Palvelut Oy perustettiin vuonna 2023 yhdella yksinkertaisella uskolla — jokainen ansaitsee puhtaan, mukavan kodin ilman stressia. Sijaitsemme Helsingissa ja palvelemme asiakkaita ympari kaupunkia.",
    yearFounded:    "Perustamisvuosi",
    teamMembers:    "Tiimin jasenet",
    revenue2024:    "Liikevaihto 2024",
    ourJourney:     "Matkamme",
    journeySubtitle:"Pienesta yrityksesta Helsingin luotetuimmaksi siivouspalveluksi — nain paasimme tahan.",
    meetTeam:       "Tutustu tiimiin",
    teamSubtitle:   "Omistautuneet ihmiset jokaisen kiiltavan puhtaan kodin takana.",
    whatWeStandFor: "Mita edustamme",
    valuesSubtitle: "Arvomme ovat kaiken toimintamme ytimessa.",
    joinTeam:       "Haluatko liittya tiimiin?",
    joinDesc:       "Etsimme aina luotettavia, ystyvallisia ihmisia, jotka ovat ylpea tyostaan. Hyva palkka, joustavat tyoajat ja tukeva tiimi.",
    getInTouch:     "Ota yhteytta",
    // ===== ABOUT PAGE — add these missing keys =====
avgRating:       "Keskimaarainen arvosana",
milestone1Title: "Perustettu Helsingissa",
milestone1Desc:  "J & S Palvelut Oy rekisteroitiin virallisesti 28. maaliskuuta 2023. Aloitimme yhdella tyontekijalla ja visiolla tarjota luotettavia siivouspalveluja Helsingissa.",
milestone2Title: "Ensimmaisen vuoden menestys",
milestone2Desc:  "Ensimmaisena vuonna saavutimme 26 000 euron liikevaihdon ja vahvan 16,7% voittomarginaalin. Tieto luotettavasta palvelustamme levisi nopeasti.",
milestone3Title: "Vahva kasvu",
milestone3Desc:  "Liikevaihto kasvoi 103,9% ja saavutti 53 000 euroa vuonna 2024. Tiimimme kasvoi kolmeen tyontekijaan ja laajensimme palveluja Helsingissa.",
milestone4Title: "Rakennamme tulevaisuutta",
milestone4Desc:  "Jatkamme asiakaskuntamme kasvattamista ja palvelujemme parantamista. Tavoitteemme on tulla Helsingin luotetuimmaksi siivouspalveluksi.",
ceoRole:         "Toimitusjohtaja ja perustaja",
ceoBio:          "Jamanta perusti J & S Palvelut Oy:n vuonna 2023. Han johtaa yrityksen vahvalla panostuksella laatupalveluun ja asiakastyytyyvaisyyteen Helsingissa.",
deputyRole:      "Varatoimitusjohtaja ja perustaja",
deputyBio:       "Shapan perusti J & S Palvelut Oy:n ja hallinnoi paivittaista toimintaa. Han varmistaa etta jokainen siivous tayttaa korkeimmat standardit.",
teamName3:       "Siivoustiimimme",
teamRole3:       "Ammattisiivoushenkilosto",
teamBio3:        "Omistautunut tiimimme on koulutettu, vakuutettu ja intohimoinen toimittamaan tahrattoman tuloksen joka kerta.",

    // ===== VALUES =====
    trustTitle:     "Luottamus",
    trustDesc:      "Jokainen siivooja on taustatarkistettu ja vakuutettu. Voit antaa meille avaimesi taysin luottavaisin mielin.",
    qualityTitle:   "Laatu",
    qualityDesc:    "Emme koskaan tee leikkauksia. Jokainen siivous tehdaan korkeimpien standardien mukaan — tai tulemme tekemaan sen uudelleen ilmaiseksi.",
    sustainTitle:   "Kestavyys",
    sustainDesc:    "Valitamme planeetasta. Kaikki tuotteemme ovat ymparistoystavallisia, biohajoavia ja turvallisia perheellesi.",
    commTitle:      "Viestinta",
    commDesc:       "Pidamme sinut ajan tasalla joka vaiheessa. Tiedat aina, milloin siivoojasi on tulossa.",

    // ===== REVIEWS PAGE =====
    reviewsBadge:   "Asiakasarvostelut",
    reviewsTitle1:  "Mita asiakkaamme",
    reviewsTitle2:  "sanovat",
    reviewsSubtitle:"Ala luota vain sanaanne — tassa on mita todelliset asiakkaat sanovat J & S Palvelut kokemuksestaan.",
    basedOn:        "Perustuen yli 2 000 arvosteluun",
    allReviews:     "Kaikki arvostelut",
    homeCleaning:   "Kotisiivous",
    deepCleanFilter:"Syvasiivous",
    officeFilter2:  "Toimisto",
    loadMore:       "Lataa lisaa arvosteluja",
    verifiedCustomer: "Vahvistettu asiakas",
    joinCustomers:  "Liity yli 2 000 tyytyvaisen asiakkaan joukkoon",
    joinDesc2:      "Koe J & S Palvelut ero itse. Varaa tanaan ja naa miksi asiakkaamme palaavat aina.",
    verifiedReviews: "Yli 2 000 vahvistettua arvostelua",

    // ===== CONTACT PAGE =====
    contactBadge:   "Ota yhteytta",
    contactTitle1:  "Haluaisimme kuulla",
    contactTitle2:  "sinusta",
    contactSubtitle:"Onko sinulla kysymys palveluistamme? Haluatko tarjouksen? Tai haluatko vain tervehtyia? Olemme taalla auttamassa!",
    sendMessage:    "Laheta meille viesti",
    formSubtitle:   "Tayta lomake ja palaamme asiaan 24 tunnin kuluessa.",
    fullName:       "Koko nimi",
    emailAddr:      "Sahkopostiosoite",
    phoneOpt:       "Puhelinnumero (valinnainen)",
    serviceInterest:"Palvelu, josta olet kiinnostunut",
    selectService:  "Valitse palvelu...",
    yourMessage:    "Viestisi",
    sendBtn:        "Laheta viesti",
    sending:        "Lahetetaan...",
    successMsg:     "Viesti lahetetty onnistuneesti!",
    successSub:     "Palaamme asiaan 24 tunnin kuluessa.",
    errorMsg:       "Jotain meni pieleen. Yrita uudelleen.",
    otherWays:      "Muut yhteydenottotavat",
    fastResponse:   "Nopea vastaus taattu",
    fastDesc:       "Vastaamme kaikkiin viesteihin 24 tunnin kuluessa — yleensa paljon nopeammin!",
    findUs:         "Loyda meidat Helsingista",
    findDesc:       "Sijaitsemme Helsingissa ja palvelemme asiakkaita ympari kaupunkia ja lahialueilla.",
    areasServed:    "Palvelualueet",
    areaDesc:       "Etkos sure kattaako alueesi? Laheta meille viesti ja kerromme!",
    workingHours:   "Ma-Pe: 8-18",
    workingSat:     "La: 9-15  |  Su: Suljettu",

    // ===== BOOKING PAGE =====
    bookingBadge:   "Helppo verkkovaraus",
    bookingTitle1:  "Varaa",
    bookingTitle2:  "siivouspalvelu",
    bookingSubtitle:"Valitse palvelu, valitse paiva ja aika, me hoidamme loput. Kestaa alle 2 minuuttia!",
    chooseService:  "1. Valitse palvelu",
    pickDateTime:   "2. Valitse paiva ja aika",
    yourDetails:    "3. Tietosi",
    confirm:        "4. Vahvista",
    chooseServiceTitle: "Valitse palvelu",
    chooseServiceDesc:  "Valitse tarpeisiisi parhaiten sopiva siivouspalvelu.",
    pickDateTitle:  "Valitse paiva ja aika",
    pickDateDesc:   "Valitse haluamasi paiva ja aika. Sunnuntait eivat ole saatavilla.",
    detailsTitle:   "Tietosi",
    detailsDesc:    "Kerro meille missa siivota ja miten tavoittaa sinut.",
    confirmTitle:   "Vahvista varauksesi",
    confirmDesc:    "Tarkista varauksen tiedot ennen vahvistamista.",
    nameRequired:   "Nimi on pakollinen",
    emailRequired:  "Sahkoposti on pakollinen",
    addrRequired:   "Osoite on pakollinen",
    selectDate:     "Valitse paiva",
    selectTime:     "Valitse aika",
    selectServiceErr: "Valitse palvelu",
    namePlaceholder:"Koko nimesi",
    emailPlaceholder:"sinun@sahkoposti.fi",
    phonePlaceholder:"+358 xx xxx xxxx",
    addrPlaceholder:"Katuosoite, kaupunki, postinumero",
    notesPlaceholder:"Erityistoiveet, allergiat, kulkuohjeet...",
    specialInstructions: "Erityisohjeet (valinnainen)",
    cleaningAddress:"Siivousosoite",
    back:           "Takaisin",
    continue:       "Jatka",
    confirmBooking: "Vahvista varaus",
    bookingConfirmed: "Varaus vahvistettu!",
    bookingThankYou:"Siivouksesi on varattu. Lahetamme vahvistuksen osoitteeseen",
    bookAnother:    "Varaa uusi siivous",
    termsNotice:    "Vahvistamalla hyvaksyt kayttoehtomme. Voit peruuttaa tai siirtaa varausta enintaan 24 tuntia ennen siivousta.",
    service:        "Palvelu",
    price:          "Hinta",
    duration:       "Kesto",
    date:           "Paiva",
    time:           "Aika",
    name:           "Nimi",
    email:          "Sahkoposti",
    address:        "Osoite",
    selectTime2:    "Valitse aika",
  }
};

// ✅ Custom hook — use in any MFE component
export function useLanguage() {
  const [language, setLanguage] = useState(
    localStorage.getItem("language") || "en"
  );

  useEffect(() => {
    const handleChange = () => {
      setLanguage(localStorage.getItem("language") || "en");
    };

    // ✅ Listen for language changes from shell
    window.addEventListener("storage", handleChange);

    // ✅ Also poll every second as backup
    const interval = setInterval(handleChange, 1000);

    return () => {
      window.removeEventListener("storage", handleChange);
      clearInterval(interval);
    };
  }, []);

  return {
    language,
    t: translations[language],
  };
}